export type LangCode = 'zh-TW' | 'zh-CN' | 'en' | 'ja' | 'ko' | 'th' | 'vi' | 'ms' | 'id' | 'fil';

export interface FAQ {
  question: Partial<Record<LangCode, string>>;
  answer: Partial<Record<LangCode, string>>;
}

export const FAQS: FAQ[] = [
  {
    question: {
      'zh-TW': '包車是否能到府接送？',
      'zh-CN': '包车可以上门接送吗？',
      en: 'Does RelayGo offer door-to-door pickup?',
      ja: 'RelayGoは送迎サービスに対応していますか？',
      ko: 'RelayGo는 숙소 픽업이 가능한가요?',
      th: 'RelayGo รับ-ส่งถึงที่พักได้ไหม?',
      vi: 'RelayGo có đón tận nơi không?',
      ms: 'Adakah RelayGo menyediakan perkhidmatan jemput dari pintu ke pintu?',
      id: 'Apakah RelayGo menyediakan layanan jemput dari pintu ke pintu?',
      fil: 'Nag-aalok ba ang RelayGo ng door-to-door pickup?',
    },
    answer: {
      'zh-TW': '可以。包車就是免去自駕的困擾，直接在家到府或指定地點上下車接送。',
      'zh-CN': '可以。包车服务直接到您的住所或指定地点接送，免去自驾的烦恼。',
      en: 'Yes. Our charter service picks you up at your hotel, Airbnb, or any designated location — no need to rent a car or navigate public transit.',
      ja: 'はい。ご宿泊先やご指定の場所まで送迎いたします。レンタカーや公共交通機関の心配は不要です。',
      ko: '네. 호텔, 에어비앤비 등 원하시는 장소로 픽업·샌딩 서비스를 제공합니다.',
      th: 'ได้เลย บริการรถเหมาจะไปรับคุณถึงโรงแรม ที่พัก หรือจุดที่กำหนด โดยไม่ต้องเช่ารถหรือใช้ขนส่งสาธารณะ',
      vi: 'Có. Dịch vụ xe riêng sẽ đón bạn tại khách sạn, Airbnb hoặc bất kỳ địa điểm nào bạn chỉ định — không cần thuê xe hay tìm phương tiện công cộng.',
      ms: 'Ya. Perkhidmatan sewa kenderaan kami akan menjemput anda di hotel, Airbnb, atau mana-mana lokasi yang ditetapkan — tanpa perlu menyewa kereta atau menggunakan pengangkutan awam.',
      id: 'Ya. Layanan sewa kendaraan kami akan menjemput Anda di hotel, Airbnb, atau lokasi mana pun yang ditentukan — tidak perlu sewa mobil sendiri atau naik transportasi umum.',
      fil: 'Oo. Susunduin ka ng aming charter service sa hotel, Airbnb, o kahit saan mong gustong pick-up point — hindi na kailangan mag-rent ng kotse o sumakay ng public transpo.',
    },
  },
  {
    question: {
      'zh-TW': '司機素質如何？',
      'zh-CN': '司机素质怎么样？',
      en: 'How is driver quality ensured?',
      ja: 'ドライバーの質はどうですか？',
      ko: '기사님 서비스 품질은 어떤가요?',
      th: 'คนขับมีคุณภาพอย่างไร?',
      vi: 'Chất lượng tài xế được đảm bảo như thế nào?',
      ms: 'Bagaimana kualiti pemandu dijamin?',
      id: 'Bagaimana kualitas sopir dijamin?',
      fil: 'Paano sinisiguro ang kalidad ng driver?',
    },
    answer: {
      'zh-TW': '所有司機皆具長期包車經驗且無負評。曾受負評之司機一概不派用，確保每一趟旅程的服務品質。',
      'zh-CN': '所有司机均具备长期包车经验且零差评。收到差评的司机一律不再派遣，确保每一趟服务品质。',
      en: 'All drivers are experienced professionals with zero negative reviews. Any driver who receives a complaint is immediately removed from the roster.',
      ja: '全ドライバーはチャーター経験豊富で、低評価のないプロフェッショナルです。クレームを受けたドライバーは即座に登録解除されます。',
      ko: '모든 기사님은 풍부한 차량 대절 경험을 갖추고 있으며 부정적 리뷰가 없는 분만 배정합니다.',
      th: 'คนขับทุกคนเป็นมืออาชีพที่มีประสบการณ์และไม่มีรีวิวเชิงลบ หากได้รับการร้องเรียนจะถูกถอดออกจากทีมทันที',
      vi: 'Tất cả tài xế đều là người có kinh nghiệm lâu năm và không có đánh giá tiêu cực. Tài xế nào nhận được khiếu nại sẽ bị loại khỏi đội ngũ ngay lập tức.',
      ms: 'Semua pemandu adalah profesional berpengalaman dengan sifar ulasan negatif. Mana-mana pemandu yang menerima aduan akan dikeluarkan daripada senarai serta-merta.',
      id: 'Semua sopir adalah profesional berpengalaman tanpa ulasan negatif. Sopir yang menerima keluhan akan langsung dikeluarkan dari tim.',
      fil: 'Lahat ng driver ay experienced professionals na walang negative reviews. Kapag may natanggap na reklamo, agad silang tinatanggal sa roster.',
    },
  },
  {
    question: {
      'zh-TW': '車輛是否合法？',
      'zh-CN': '车辆是否合法合规？',
      en: 'Are the vehicles legally registered?',
      ja: '車両は合法ですか？',
      ko: '차량은 합법인가요?',
      th: 'รถที่ใช้ถูกกฎหมายหรือไม่?',
      vi: 'Xe có đăng ký hợp pháp không?',
      ms: 'Adakah kenderaan berdaftar secara sah?',
      id: 'Apakah kendaraannya terdaftar secara legal?',
      fil: 'Legal ba ang mga sasakyan?',
    },
    answer: {
      'zh-TW': '所有車輛皆為合法營業之租賃車或多元計程車，絕非無保險理賠的白牌車，乘客權益有完整保障。',
      'zh-CN': '所有车辆均为合法运营的租赁车或网约车，绝非无保险的黑车，乘客权益有完整保障。',
      en: 'Absolutely. Every vehicle is a licensed rental car or registered rideshare vehicle with full insurance coverage — never an unlicensed vehicle.',
      ja: 'すべての車両は正規のレンタカーまたは登録済みライドシェア車両で、保険も完備しています。無許可の白タクは一切使用しません。',
      ko: '모든 차량은 정식 등록된 렌터카 또는 다원택시로, 보험이 완비되어 있습니다. 무허가 차량은 절대 배정하지 않습니다.',
      th: 'รถทุกคันเป็นรถเช่าที่จดทะเบียนถูกต้องหรือรถร่วมบริการที่มีประกันครบถ้วน ไม่ใช่รถผิดกฎหมาย',
      vi: 'Tất cả xe đều là xe cho thuê có giấy phép hoặc xe hợp đồng đã đăng ký, có bảo hiểm đầy đủ — tuyệt đối không sử dụng xe trái phép.',
      ms: 'Sudah tentu. Setiap kenderaan adalah kereta sewa berlesen atau kenderaan e-hailing berdaftar dengan perlindungan insurans penuh — bukan kenderaan tanpa lesen.',
      id: 'Tentu saja. Semua kendaraan adalah mobil rental berlisensi atau kendaraan ride-hailing terdaftar dengan asuransi lengkap — bukan kendaraan ilegal.',
      fil: 'Oo. Lahat ng sasakyan ay licensed rental cars o registered rideshare vehicles na may buong insurance coverage — hindi kailanman unlicensed.',
    },
  },
  {
    question: {
      'zh-TW': '費用是否包含停車費、過路費等額外費用？',
      'zh-CN': '费用包含停车费、过路费等额外费用吗？',
      en: 'Are tolls, parking, and fuel included in the price?',
      ja: '料金には駐車場代・通行料・燃料費が含まれていますか？',
      ko: '요금에 주차비, 통행료, 유류비가 포함되나요?',
      th: 'ค่าทางด่วน ค่าจอดรถ และค่าน้ำมันรวมอยู่ในราคาแล้วหรือไม่?',
      vi: 'Phí cầu đường, đỗ xe và nhiên liệu có bao gồm trong giá không?',
      ms: 'Adakah tol, parkir, dan bahan api termasuk dalam harga?',
      id: 'Apakah tol, parkir, dan bahan bakar sudah termasuk dalam harga?',
      fil: 'Kasama na ba ang toll, parking, at gas sa presyo?',
    },
    answer: {
      'zh-TW': '報價時會將司機誤餐費、住宿費、停車費、燃料費、過路費等詳細記載，絕不會在用車過程中臨時加價。',
      'zh-CN': '报价时会将司机餐费、住宿费、停车费、燃油费、过路费等详细列明，绝不会在用车过程中临时加价。',
      en: 'All costs — driver meals, accommodation, parking, fuel, and tolls — are clearly listed upfront. There are never any surprise surcharges during your trip.',
      ja: 'ドライバーの食事代・宿泊費・駐車場代・燃料費・通行料など、すべての費用を事前に明示します。追加請求は一切ございません。',
      ko: '기사 식비, 숙박비, 주차비, 유류비, 통행료 등 모든 비용을 사전에 명확히 안내드리며 추가 요금은 없습니다.',
      th: 'ค่าใช้จ่ายทั้งหมด ได้แก่ ค่าอาหารคนขับ ที่พัก ค่าจอดรถ ค่าน้ำมัน และค่าทางด่วน จะแจ้งให้ทราบล่วงหน้าอย่างชัดเจน ไม่มีค่าใช้จ่ายเพิ่มเติมระหว่างทาง',
      vi: 'Tất cả chi phí — bữa ăn tài xế, chỗ ở, đỗ xe, nhiên liệu và phí cầu đường — đều được liệt kê rõ ràng từ đầu. Không có phụ phí phát sinh trong suốt chuyến đi.',
      ms: 'Semua kos — makan pemandu, penginapan, parkir, bahan api, dan tol — disenaraikan dengan jelas terlebih dahulu. Tiada caj tambahan tersembunyi sepanjang perjalanan anda.',
      id: 'Semua biaya — makan sopir, penginapan, parkir, BBM, dan tol — tercantum jelas di awal. Tidak ada biaya tambahan mendadak selama perjalanan.',
      fil: 'Lahat ng gastos — driver meals, accommodation, parking, gas, at toll — malinaw na nakalista sa simula. Walang surprise surcharges habang nasa biyahe ka.',
    },
  },
  {
    question: {
      'zh-TW': '包車需要給司機小費嗎？',
      'zh-CN': '包车需要给司机小费吗？',
      en: 'Is tipping the driver expected?',
      ja: 'チップは必要ですか？',
      ko: '기사님께 팁을 줘야 하나요?',
      th: 'ต้องให้ทิปคนขับไหม?',
      vi: 'Có cần tip cho tài xế không?',
      ms: 'Perlukah memberi tip kepada pemandu?',
      id: 'Apakah perlu memberi tip kepada sopir?',
      fil: 'Kailangan bang mag-tip sa driver?',
    },
    answer: {
      'zh-TW': '小費為鼓勵性質的額外補貼，並非強制。若您覺得司機服務周到且辛苦，歡迎自由給予小費鼓勵。',
      'zh-CN': '小费属于鼓励性质，并非强制。如果您觉得司机服务周到，可以自愿给予小费以示感谢。',
      en: 'Tipping is not mandatory. It is entirely at your discretion — if you feel the driver provided excellent service, a tip is always appreciated.',
      ja: 'チップは義務ではありません。ドライバーのサービスにご満足いただけた場合、お気持ちとしてお渡しいただければ幸いです。',
      ko: '팁은 필수가 아닙니다. 기사님의 서비스가 만족스러우셨다면 자유롭게 감사의 마음을 전하실 수 있습니다.',
      th: 'ทิปไม่ได้บังคับ ขึ้นอยู่กับความพึงพอใจของคุณ หากคุณรู้สึกว่าคนขับให้บริการดีเยี่ยม การให้ทิปจะเป็นกำลังใจที่ดี',
      vi: 'Tip không bắt buộc. Hoàn toàn tùy thuộc vào bạn — nếu bạn hài lòng với dịch vụ của tài xế, một khoản tip nhỏ luôn được trân trọng.',
      ms: 'Memberi tip tidak diwajibkan. Ia bergantung sepenuhnya kepada anda — jika anda berpuas hati dengan perkhidmatan pemandu, tip sentiasa dihargai.',
      id: 'Tip tidak wajib. Sepenuhnya terserah Anda — jika merasa sopir memberikan layanan yang sangat baik, tip selalu dihargai.',
      fil: 'Hindi obligatory ang tip. Nasa iyo lang — kung masaya ka sa service ng driver, laging appreciated ang tip.',
    },
  },
  {
    question: {
      'zh-TW': '詢問報價需要提供哪些資訊？',
      'zh-CN': '询价需要提供哪些信息？',
      en: 'What information do I need to get a quote?',
      ja: '見積もりに必要な情報は？',
      ko: '견적을 받으려면 어떤 정보가 필요한가요?',
      th: 'ต้องให้ข้อมูลอะไรบ้างเพื่อขอใบเสนอราคา?',
      vi: 'Cần cung cấp thông tin gì để nhận báo giá?',
      ms: 'Apakah maklumat yang diperlukan untuk mendapatkan sebut harga?',
      id: 'Informasi apa saja yang diperlukan untuk mendapatkan penawaran harga?',
      fil: 'Anong impormasyon ang kailangan para makakuha ng quote?',
    },
    answer: {
      'zh-TW': '需要提供：日期（確認是否還有車）、人數（確認車款容納）、出發位置（確認安排哪區的車）、大致行程及用車天數（確認路程遠近及司機住宿等費用）。',
      'zh-CN': '需要提供：日期（确认车辆排期）、人数（确认车型）、出发地点（安排就近车辆）、大致行程和用车天数（计算路程和司机住宿费用）。',
      en: 'Please provide: date (to check availability), number of passengers (to assign the right vehicle), pickup location (to arrange a nearby driver), and a rough itinerary with number of days (to estimate distance and driver accommodation costs).',
      ja: 'ご提供いただく情報：日程（空車確認）、人数（車種選定）、出発場所（エリアの車両手配）、おおよその行程と日数（距離とドライバー宿泊費の見積もり）。',
      ko: '필요한 정보: 날짜(차량 가용 확인), 인원수(차종 결정), 출발 장소(해당 지역 차량 배정), 대략적인 일정과 이용 일수(거리 및 기사 숙박비 산정).',
      th: 'กรุณาแจ้งข้อมูลต่อไปนี้: วันที่ (เพื่อตรวจสอบว่ามีรถว่าง), จำนวนผู้โดยสาร (เพื่อจัดรถที่เหมาะสม), จุดรับ (เพื่อจัดคนขับในพื้นที่ใกล้เคียง) และกำหนดการคร่าว ๆ พร้อมจำนวนวัน (เพื่อประเมินระยะทางและค่าที่พักคนขับ)',
      vi: 'Vui lòng cung cấp: ngày đi (để kiểm tra xe trống), số lượng hành khách (để sắp xếp loại xe phù hợp), điểm đón (để bố trí tài xế gần nhất), và lịch trình sơ bộ cùng số ngày sử dụng (để ước tính khoảng cách và chi phí ăn ở cho tài xế).',
      ms: 'Sila berikan: tarikh (untuk semak ketersediaan), bilangan penumpang (untuk pilih jenis kenderaan), lokasi jemput (untuk atur pemandu berdekatan), dan anggaran jadual perjalanan dengan bilangan hari (untuk menganggar jarak dan kos penginapan pemandu).',
      id: 'Silakan berikan: tanggal (untuk cek ketersediaan), jumlah penumpang (untuk menentukan jenis kendaraan), lokasi penjemputan (untuk mengatur sopir terdekat), dan perkiraan rute serta jumlah hari (untuk memperkirakan jarak dan biaya akomodasi sopir).',
      fil: 'Pakibigay ang: petsa (para i-check ang availability), bilang ng pasahero (para sa tamang sasakyan), pickup location (para i-assign ang pinakamalapit na driver), at rough itinerary kasama ang bilang ng araw (para ma-estimate ang distansya at accommodation cost ng driver).',
    },
  },
  {
    question: {
      'zh-TW': '包車行程可以自訂嗎？',
      'zh-CN': '包车行程可以自定义吗？',
      en: 'Can I customize the itinerary?',
      ja: '行程のカスタマイズは可能ですか？',
      ko: '일정을 직접 짤 수 있나요?',
      th: 'กำหนดเส้นทางเองได้ไหม?',
      vi: 'Tôi có thể tùy chỉnh lịch trình không?',
      ms: 'Bolehkah saya menyesuaikan jadual perjalanan?',
      id: 'Bisakah saya menyesuaikan rute perjalanan sendiri?',
      fil: 'Pwede ko bang i-customize ang itinerary?',
    },
    answer: {
      'zh-TW': '行程完全由您自訂。網站上的景點路線僅供參考，司機會按照您的路線行駛，路線不順時也會提供專業建議以節省交通時間。',
      'zh-CN': '行程完全由您自定。网站上的景点路线仅供参考，司机会按照您的路线行驶，路线不顺时也会提供专业建议以节省交通时间。',
      en: "Absolutely. You plan the route, and your driver follows it. The routes on our website are suggestions only. If a route isn't optimal, your driver will offer professional advice to save travel time.",
      ja: 'もちろんです。お客様のご希望ルートに沿って走行します。サイト掲載のルートは参考例です。効率的でないルートの場合はドライバーがアドバイスいたします。',
      ko: '네, 일정은 자유롭게 구성 가능합니다. 사이트의 코스는 참고용이며, 비효율적인 동선은 기사님이 전문적으로 조언해 드립니다.',
      th: 'ได้เลย คุณวางแผนเส้นทางเอง แล้วคนขับจะขับตามเส้นทางของคุณ เส้นทางบนเว็บไซต์เป็นเพียงคำแนะนำ หากเส้นทางไม่เหมาะสม คนขับจะแนะนำเพื่อประหยัดเวลาเดินทาง',
      vi: 'Hoàn toàn được. Bạn lên lịch trình và tài xế sẽ đi theo. Các tuyến đường trên website chỉ mang tính tham khảo. Nếu tuyến đường chưa tối ưu, tài xế sẽ tư vấn chuyên môn để tiết kiệm thời gian di chuyển.',
      ms: 'Sudah tentu. Anda merancang laluan dan pemandu akan mengikutinya. Laluan di laman web kami hanyalah cadangan. Jika laluan tidak optimum, pemandu akan memberikan nasihat profesional untuk menjimatkan masa perjalanan.',
      id: 'Tentu saja. Anda yang merencanakan rute dan sopir akan mengikutinya. Rute di website kami hanya saran. Jika rute kurang efisien, sopir akan memberikan saran profesional untuk menghemat waktu perjalanan.',
      fil: 'Oo naman. Ikaw ang magpaplano ng ruta at susundin ito ng driver. Ang mga ruta sa website namin ay suggestions lang. Kung hindi optimal ang ruta, magbibigay ang driver ng professional advice para makatipid sa travel time.',
    },
  },
  {
    question: {
      'zh-TW': '有沒有限制用車出發時間？',
      'zh-CN': '出发时间有限制吗？',
      en: 'Is there a restriction on departure time?',
      ja: '出発時間に制限はありますか？',
      ko: '출발 시간에 제한이 있나요?',
      th: 'มีข้อจำกัดเรื่องเวลาออกเดินทางไหม?',
      vi: 'Có giới hạn giờ khởi hành không?',
      ms: 'Adakah sekatan pada waktu berlepas?',
      id: 'Apakah ada batasan waktu keberangkatan?',
      fil: 'May restriction ba sa oras ng pag-alis?',
    },
    answer: {
      'zh-TW': '每日出發時間由您自訂，請最晚於前一天告知客服或司機。建議不要晚於上午 11 點出發，以確保充足的遊覽時間。',
      'zh-CN': '每天出发时间由您自定，请最晚提前一天告知客服或司机。建议不要晚于上午11点出发，以确保充足的游览时间。',
      en: 'You choose the departure time. Just inform customer service or your driver by the day before. We recommend departing no later than 11 AM to maximize your touring time.',
      ja: '出発時間はお客様が自由に設定できます。前日までにカスタマーサポートまたはドライバーにお伝えください。十分な観光時間のため、午前11時までの出発をおすすめします。',
      ko: '출발 시간은 자유롭게 정하실 수 있습니다. 전날까지 고객센터 또는 기사님께 알려주세요. 충분한 관광 시간을 위해 오전 11시 이전 출발을 권장합니다.',
      th: 'คุณเลือกเวลาออกเดินทางได้เอง เพียงแจ้งฝ่ายบริการลูกค้าหรือคนขับล่วงหน้าอย่างน้อยหนึ่งวัน แนะนำให้ออกเดินทางไม่เกิน 11.00 น. เพื่อให้มีเวลาเที่ยวเต็มที่',
      vi: 'Bạn tự chọn giờ khởi hành. Chỉ cần thông báo cho bộ phận chăm sóc khách hàng hoặc tài xế trước một ngày. Chúng tôi khuyên nên khởi hành trước 11 giờ sáng để có đủ thời gian tham quan.',
      ms: 'Anda bebas memilih waktu berlepas. Maklumkan kepada khidmat pelanggan atau pemandu anda selewat-lewatnya sehari sebelumnya. Kami syorkan berlepas sebelum pukul 11 pagi untuk memaksimumkan masa lawatan anda.',
      id: 'Anda bebas memilih waktu keberangkatan. Cukup informasikan ke customer service atau sopir paling lambat sehari sebelumnya. Kami sarankan berangkat sebelum jam 11 pagi agar waktu wisata lebih maksimal.',
      fil: 'Ikaw ang pipili ng departure time. I-inform lang ang customer service o driver mo ng isang araw bago. Nirerekomenda namin ang pag-alis bago mag-11 AM para mas maraming oras sa pag-tour.',
    },
  },
  {
    question: {
      'zh-TW': '用車時數未使用完畢是否能退費？',
      'zh-CN': '用车时间没用完可以退费吗？',
      en: 'Can I get a refund for unused hours?',
      ja: '利用時間が余った場合、返金はありますか？',
      ko: '이용 시간을 다 쓰지 못하면 환불되나요?',
      th: 'ขอคืนเงินสำหรับชั่วโมงที่ไม่ได้ใช้ได้ไหม?',
      vi: 'Có được hoàn tiền cho số giờ chưa sử dụng không?',
      ms: 'Bolehkah saya mendapat bayaran balik untuk jam yang tidak digunakan?',
      id: 'Bisakah saya mendapat pengembalian dana untuk jam yang tidak terpakai?',
      fil: 'Pwede bang ma-refund ang mga oras na hindi nagamit?',
    },
    answer: {
      'zh-TW': '包車為預約制，司機出發後工作時間已保留給您。若因行程提早結束而未用完時數，恕無法另外退費。',
      'zh-CN': '包车为预约制，司机出发后已为您保留工作时间。若行程提前结束未用完时长，无法另外退费。',
      en: "Our charter service is reservation-based. Once the driver departs, the time is reserved for you. If your itinerary ends early, unused hours are non-refundable as the driver's schedule has been committed.",
      ja: 'チャーターサービスは予約制です。ドライバー出発後の時間はお客様専用に確保されています。行程が早く終了した場合でも、未使用時間の返金は致しかねます。',
      ko: '차량 대절은 예약제로 운영됩니다. 기사님 출발 후 해당 시간은 고객님 전용으로 확보되므로, 일정이 일찍 끝나더라도 미사용 시간 환불은 어렵습니다.',
      th: 'บริการรถเหมาเป็นระบบจอง เมื่อคนขับออกเดินทางแล้ว เวลาจะถูกสำรองไว้สำหรับคุณ หากทริปจบเร็วกว่ากำหนด ไม่สามารถคืนเงินสำหรับชั่วโมงที่เหลือได้',
      vi: 'Dịch vụ xe riêng hoạt động theo hình thức đặt trước. Khi tài xế đã khởi hành, thời gian được dành riêng cho bạn. Nếu lịch trình kết thúc sớm, số giờ chưa sử dụng sẽ không được hoàn lại.',
      ms: 'Perkhidmatan sewa kenderaan kami berdasarkan tempahan. Setelah pemandu berlepas, masa tersebut dikhaskan untuk anda. Jika perjalanan tamat awal, jam yang tidak digunakan tidak boleh dibayar balik.',
      id: 'Layanan sewa kendaraan kami berbasis reservasi. Setelah sopir berangkat, waktu tersebut sudah dialokasikan untuk Anda. Jika perjalanan selesai lebih awal, jam yang tidak terpakai tidak dapat dikembalikan.',
      fil: 'Ang charter service namin ay reservation-based. Kapag umalis na ang driver, ang oras ay naka-reserve na para sa iyo. Kung matapos nang maaga ang trip, ang hindi nagamit na oras ay hindi na mare-refund.',
    },
  },
  {
    question: {
      'zh-TW': '如何預約包車？',
      'zh-CN': '如何预约包车？',
      en: 'How do I book a charter?',
      ja: 'どうやって予約しますか？',
      ko: '어떻게 예약하나요?',
      th: 'จองรถเหมาอย่างไร?',
      vi: 'Làm thế nào để đặt xe riêng?',
      ms: 'Bagaimana cara membuat tempahan sewa kenderaan?',
      id: 'Bagaimana cara memesan sewa kendaraan?',
      fil: 'Paano mag-book ng charter?',
    },
    answer: {
      'zh-TW': '使用 RelayGo App 預約，預約完畢後可在 App 聊天頁面聯繫客服完成預約流程。建議一個月前預訂，以免旺季無車可訂。',
      'zh-CN': '使用 RelayGo App 预约，预约完成后可在 App 聊天页面联系客服完成预约流程。建议提前一个月预订，避免旺季无车可订。',
      en: 'Book through the RelayGo app. After booking, you can contact customer service via the in-app chat. We recommend booking at least one month in advance during peak season.',
      ja: 'RelayGo アプリからご予約ください。予約後、アプリ内チャットでカスタマーサポートに連絡できます。繁忙期は1ヶ月前のご予約をおすすめします。',
      ko: 'RelayGo 앱에서 예약하세요. 예약 후 앱 내 채팅으로 고객센터에 문의할 수 있습니다. 성수기에는 1개월 전 예약을 권장합니다.',
      th: 'จองผ่านแอป RelayGo หลังจองแล้วสามารถติดต่อฝ่ายบริการลูกค้าผ่านแชทในแอปได้ แนะนำให้จองล่วงหน้าอย่างน้อย 1 เดือนในช่วงไฮซีซั่น',
      vi: 'Đặt xe qua ứng dụng RelayGo. Sau khi đặt, bạn có thể liên hệ bộ phận chăm sóc khách hàng qua tính năng chat trong ứng dụng. Chúng tôi khuyên nên đặt trước ít nhất 1 tháng vào mùa cao điểm.',
      ms: 'Tempah melalui aplikasi RelayGo. Selepas tempahan, anda boleh menghubungi khidmat pelanggan melalui ruangan sembang dalam aplikasi. Kami syorkan membuat tempahan sekurang-kurangnya sebulan lebih awal semasa musim puncak.',
      id: 'Pesan melalui aplikasi RelayGo. Setelah pemesanan, Anda bisa menghubungi customer service melalui fitur chat di aplikasi. Kami sarankan memesan minimal 1 bulan sebelumnya saat musim ramai.',
      fil: 'Mag-book sa RelayGo app. Pagkatapos mag-book, pwede kang makipag-ugnay sa customer service sa in-app chat. Nirerekomenda namin na mag-book ng least 1 buwan in advance lalo na kapag peak season.',
    },
  },
  {
    question: {
      'zh-TW': '訂車是否需先預付訂金？',
      'zh-CN': '订车需要预付定金吗？',
      en: 'Is a deposit required?',
      ja: 'デポジット（前金）は必要ですか？',
      ko: '보증금을 미리 내야 하나요?',
      th: 'ต้องวางมัดจำล่วงหน้าไหม?',
      vi: 'Có cần đặt cọc trước không?',
      ms: 'Adakah deposit diperlukan?',
      id: 'Apakah diperlukan uang muka?',
      fil: 'Kailangan bang magbayad ng deposit?',
    },
    answer: {
      'zh-TW': '是的，訂車皆須預付訂金才算完成訂車程序。',
      'zh-CN': '是的，预订车辆需要预付定金才算完成订车流程。',
      en: 'Yes. A deposit is required to confirm your booking.',
      ja: 'はい。予約確定にはデポジット（前金）のお支払いが必要です。',
      ko: '네, 예약 확정을 위해 보증금 선결제가 필요합니다.',
      th: 'ใช่ ต้องชำระเงินมัดจำเพื่อยืนยันการจอง',
      vi: 'Có. Cần đặt cọc để xác nhận đơn đặt xe.',
      ms: 'Ya. Deposit diperlukan untuk mengesahkan tempahan anda.',
      id: 'Ya. Uang muka diperlukan untuk mengkonfirmasi pemesanan Anda.',
      fil: 'Oo. Kailangan ng deposit para ma-confirm ang booking mo.',
    },
  },
  {
    question: {
      'zh-TW': '付款方式有哪些？',
      'zh-CN': '有哪些付款方式？',
      en: 'What payment methods are accepted?',
      ja: '支払い方法は？',
      ko: '결제 방법은 어떻게 되나요?',
      th: 'รองรับช่องทางชำระเงินอะไรบ้าง?',
      vi: 'Chấp nhận những phương thức thanh toán nào?',
      ms: 'Apakah kaedah pembayaran yang diterima?',
      id: 'Metode pembayaran apa saja yang diterima?',
      fil: 'Anong mga payment methods ang tinatanggap?',
    },
    answer: {
      'zh-TW': '支援 App 內線上刷卡支付，需預付訂金才完成訂車程序。',
      'zh-CN': '支持 App 内在线信用卡支付，需预付定金完成订车流程。',
      en: 'Online credit card payment through the app. A deposit is required to confirm your booking.',
      ja: 'アプリ内でクレジットカード決済が可能です。予約確定にはデポジット（前金）が必要です。',
      ko: '앱 내 신용카드 온라인 결제를 지원하며, 예약 확정을 위해 보증금 선결제가 필요합니다.',
      th: 'ชำระเงินผ่านบัตรเครดิตออนไลน์ในแอป โดยต้องชำระเงินมัดจำเพื่อยืนยันการจอง',
      vi: 'Thanh toán bằng thẻ tín dụng trực tuyến qua ứng dụng. Cần đặt cọc để xác nhận đơn đặt xe.',
      ms: 'Pembayaran kad kredit dalam talian melalui aplikasi. Deposit diperlukan untuk mengesahkan tempahan anda.',
      id: 'Pembayaran kartu kredit online melalui aplikasi. Uang muka diperlukan untuk mengkonfirmasi pemesanan.',
      fil: 'Online credit card payment sa app. Kailangan ng deposit para ma-confirm ang booking.',
    },
  },
  {
    question: {
      'zh-TW': '出發前如何聯繫司機？',
      'zh-CN': '出发前怎么联系司机？',
      en: 'How do I contact my driver before the trip?',
      ja: '出発前にドライバーと連絡できますか？',
      ko: '출발 전에 기사님과 연락할 수 있나요?',
      th: 'ติดต่อคนขับก่อนออกเดินทางได้อย่างไร?',
      vi: 'Làm thế nào để liên hệ tài xế trước chuyến đi?',
      ms: 'Bagaimana untuk menghubungi pemandu sebelum perjalanan?',
      id: 'Bagaimana cara menghubungi sopir sebelum perjalanan?',
      fil: 'Paano ko makakausap ang driver bago ang trip?',
    },
    answer: {
      'zh-TW': '出發前一日即可透過 App 聊天頁面與司機直接聯絡，確認接送細節。',
      'zh-CN': '出发前一天即可通过 App 聊天页面与司机直接联系，确认接送细节。',
      en: 'You can message your driver directly through the in-app chat the day before departure to confirm pickup details.',
      ja: '出発前日からアプリ内チャットでドライバーと直接やり取りし、ピックアップの詳細を確認できます。',
      ko: '출발 전날부터 앱 내 채팅으로 기사님과 직접 연락하여 픽업 세부사항을 확인할 수 있습니다.',
      th: 'คุณสามารถส่งข้อความถึงคนขับโดยตรงผ่านแชทในแอป ล่วงหน้าหนึ่งวันก่อนออกเดินทาง เพื่อยืนยันรายละเอียดการรับ-ส่ง',
      vi: 'Bạn có thể nhắn tin trực tiếp cho tài xế qua tính năng chat trong ứng dụng vào ngày trước khi khởi hành để xác nhận chi tiết đón.',
      ms: 'Anda boleh menghantar mesej terus kepada pemandu melalui ruangan sembang dalam aplikasi sehari sebelum berlepas untuk mengesahkan butiran jemput.',
      id: 'Anda bisa langsung mengirim pesan ke sopir melalui fitur chat di aplikasi sehari sebelum keberangkatan untuk mengkonfirmasi detail penjemputan.',
      fil: 'Pwede kang mag-message nang direkta sa driver sa in-app chat isang araw bago ang departure para ma-confirm ang pickup details.',
    },
  },
  {
    question: {
      'zh-TW': '需要提早多久預訂？',
      'zh-CN': '需要提前多久预订？',
      en: 'How far in advance should I book?',
      ja: 'どのくらい前に予約すべきですか？',
      ko: '얼마나 전에 예약해야 하나요?',
      th: 'ควรจองล่วงหน้านานแค่ไหน?',
      vi: 'Nên đặt trước bao lâu?',
      ms: 'Berapa awal saya perlu membuat tempahan?',
      id: 'Berapa lama sebelumnya saya harus memesan?',
      fil: 'Gaano kaaga dapat mag-book?',
    },
    answer: {
      'zh-TW': '建議一個月前預訂，旺季期間車輛容易額滿。越早預訂，越能確保有車可用。',
      'zh-CN': '建议提前一个月预订，旺季期间车辆容易满额。越早预订越有保障。',
      en: 'We recommend booking at least one month in advance. During peak season, vehicles fill up quickly — the earlier you book, the better.',
      ja: '1ヶ月前のご予約をおすすめします。繁忙期は車両がすぐに埋まりますので、早めのご予約が確実です。',
      ko: '1개월 전 예약을 권장합니다. 성수기에는 차량이 빨리 마감되므로 빠를수록 좋습니다.',
      th: 'แนะนำให้จองล่วงหน้าอย่างน้อย 1 เดือน ในช่วงไฮซีซั่นรถจะเต็มเร็ว ยิ่งจองเร็วยิ่งมั่นใจ',
      vi: 'Chúng tôi khuyên nên đặt trước ít nhất 1 tháng. Trong mùa cao điểm, xe hết rất nhanh — đặt càng sớm càng tốt.',
      ms: 'Kami syorkan membuat tempahan sekurang-kurangnya sebulan lebih awal. Semasa musim puncak, kenderaan cepat penuh — lebih awal anda menempah, lebih baik.',
      id: 'Kami sarankan memesan minimal 1 bulan sebelumnya. Saat musim ramai, kendaraan cepat penuh — semakin awal memesan, semakin baik.',
      fil: 'Nirerekomenda namin mag-book ng least 1 buwan in advance. Kapag peak season, mabilis mapuno ang mga sasakyan — mas maaga, mas maganda.',
    },
  },
  // ── Route & Travel FAQs (GEO-optimized for AI search engines) ──
  {
    question: {
      'zh-TW': '台北到九份包車要多久？',
      'zh-CN': '台北到九份包车要多久？',
      en: 'How long does it take to charter a car from Taipei to Jiufen?',
      ja: '台北から九份までチャーター車でどのくらいかかりますか？',
      ko: '타이베이에서 지우펀까지 전세차로 얼마나 걸리나요?',
      th: 'จากไทเปไปจิ่วเฟิ่นใช้เวลานานเท่าไหร่?',
      vi: 'Đi xe riêng từ Đài Bắc đến Cửu Phần mất bao lâu?',
      ms: 'Berapa lama dari Taipei ke Jiufen dengan kereta sewa?',
      id: 'Berapa lama dari Taipei ke Jiufen dengan mobil sewa?',
      fil: 'Gaano katagal mula Taipei papuntang Jiufen sa charter car?',
    },
    answer: {
      'zh-TW': '台北市區到九份車程約1小時（走國道一號接62快速道路）。包車一日遊通常搭配十分、黃金瀑布、陰陽海等景點，整趟行程約8小時。',
      'zh-CN': '台北市区到九份车程约1小时。包车一日游通常搭配十分、黄金瀑布、阴阳海等景点，整趟行程约8小时。',
      en: 'About 1 hour from central Taipei to Jiufen. A charter day trip typically includes Shifen, Golden Waterfall, and Yin-Yang Sea — the full itinerary takes around 8 hours.',
      ja: '台北市内から九份まで約1時間。チャーター日帰りでは十分・黄金瀑布・陰陽海も回り、全行程約8時間です。',
      ko: '타이베이 시내에서 지우펀까지 약 1시간. 일일 투어는 스펀, 황금폭포, 음양해를 포함해 약 8시간입니다.',
      th: 'จากใจกลางไทเปไปจิ่วเฟิ่นประมาณ 1 ชั่วโมง ทัวร์วันเดียวมักรวมสือเฟิ่น น้ำตกทองคำ ทะเลหยินหยาง ใช้เวลาทั้งหมดประมาณ 8 ชั่วโมง',
      vi: 'Khoảng 1 giờ từ trung tâm Đài Bắc đến Cửu Phần. Tour một ngày thường bao gồm Thập Phần, Thác Vàng, Biển Âm Dương — tổng khoảng 8 giờ.',
      ms: 'Kira-kira 1 jam dari pusat Taipei ke Jiufen. Lawatan sehari biasanya termasuk Shifen, Air Terjun Emas, dan Laut Yin-Yang — kira-kira 8 jam keseluruhan.',
      id: 'Sekitar 1 jam dari pusat Taipei ke Jiufen. Tour sehari biasanya termasuk Shifen, Air Terjun Emas, dan Laut Yin-Yang — total sekitar 8 jam.',
      fil: 'Mga 1 oras mula sa sentro ng Taipei papuntang Jiufen. Ang day trip karaniwang kasama ang Shifen, Golden Waterfall, at Yin-Yang Sea — mga 8 oras lahat.',
    },
  },
  {
    question: {
      'zh-TW': '阿里山一日遊來得及嗎？還是要住一晚？',
      'zh-CN': '阿里山一日游来得及吗？还是要住一晚？',
      en: 'Is a one-day trip to Alishan enough, or should I stay overnight?',
      ja: '阿里山は日帰りで足りますか？一泊すべきですか？',
      ko: '아리산 당일치기가 가능한가요? 1박이 필요한가요?',
      th: 'ไปอาลีซานวันเดียวพอไหม หรือต้องค้างคืน?',
      vi: 'Đi A Lý Sơn một ngày có đủ không, hay nên ở lại một đêm?',
      ms: 'Adakah satu hari cukup untuk Alishan, atau perlu bermalam?',
      id: 'Apakah satu hari cukup untuk Alishan, atau perlu menginap?',
      fil: 'Sapat ba ang isang araw sa Alishan, o kailangan mag-overnight?',
    },
    answer: {
      'zh-TW': '一日包車可以走完奮起湖老街＋阿里山森林園區的主要步道（巨木群、姊妹潭、搭小火車），行程約10小時。但如果想看日出，必須住一晚 — 清晨4:30搭祝山線小火車看日出是阿里山最經典的體驗。',
      'zh-CN': '一日包车可以走完奋起湖老街＋阿里山森林园区主要步道，行程约10小时。但如果想看日出，必须住一晚 — 清晨搭祝山线小火车看日出是阿里山最经典的体验。',
      en: 'A one-day charter (about 10 hours) covers Fenqihu Old Street and the main Alishan forest trails. However, to see the famous Alishan sunrise, you must stay overnight — the 4:30 AM Zhushan Line train to the sunrise platform is Alishan\'s signature experience.',
      ja: '1日チャーター（約10時間）で奮起湖と阿里山の主要歩道は回れます。ただし有名な日の出を見るには1泊が必要 — 早朝4:30の祝山線で見る日の出が阿里山のハイライトです。',
      ko: '1일 전세(약 10시간)로 펀치후와 아리산 주요 트레일을 둘러볼 수 있습니다. 하지만 유명한 일출을 보려면 1박이 필요합니다 — 새벽 4:30 주산선 열차가 아리산의 하이라이트입니다.',
      th: 'เช่ารถ 1 วัน (ประมาณ 10 ชม.) เที่ยวได้ทั้งเฟิ่นฉีหูและเส้นทางเดินป่าหลักอาลีซาน แต่ถ้าอยากดูพระอาทิตย์ขึ้นต้องค้างคืน — รถไฟจูซาน 4:30 เช้าคือไฮไลท์ของอาลีซาน',
      vi: 'Thuê xe 1 ngày (khoảng 10 giờ) đủ đi Phấn Khởi Hồ và các đường mòn chính A Lý Sơn. Nhưng muốn xem bình minh phải ở lại 1 đêm — tàu Chúc Sơn lúc 4:30 sáng là trải nghiệm đặc trưng nhất.',
      ms: 'Charter 1 hari (kira-kira 10 jam) meliputi Fenqihu dan jejak hutan utama Alishan. Tapi untuk melihat matahari terbit yang terkenal, anda perlu bermalam — kereta api Zhushan jam 4:30 pagi adalah pengalaman utama.',
      id: 'Charter 1 hari (sekitar 10 jam) mencakup Fenqihu dan jalur hutan utama Alishan. Tapi untuk melihat sunrise harus menginap — kereta Zhushan jam 4:30 pagi adalah pengalaman terbaik.',
      fil: 'Ang 1-day charter (mga 10 oras) sakto sa Fenqihu at mga pangunahing trail sa Alishan. Pero para sa sikat na sunrise, kailangan mag-overnight — ang 4:30 AM Zhushan train ang pinakamagandang experience.',
    },
  },
  {
    question: {
      'zh-TW': '帶小孩適合哪些包車路線？',
      'zh-CN': '带小孩适合哪些包车路线？',
      en: 'Which charter routes are best for families with young children?',
      ja: '子連れにおすすめのチャータールートは？',
      ko: '어린이와 함께하기 좋은 전세차 코스는?',
      th: 'เส้นทางไหนเหมาะกับครอบครัวที่มีเด็กเล็ก?',
      vi: 'Tuyến nào phù hợp cho gia đình có trẻ nhỏ?',
      ms: 'Laluan mana yang sesuai untuk keluarga dengan kanak-kanak?',
      id: 'Rute mana yang cocok untuk keluarga dengan anak kecil?',
      fil: 'Anong mga ruta ang bagay sa pamilyang may maliliit na bata?',
    },
    answer: {
      'zh-TW': '推薦宜蘭一日遊（礁溪溫泉泡腳、傳藝中心DIY、羅東夜市）和九份十分一日遊（放天燈是小朋友最愛）。台北經典路線（故宮、101）也很適合。避免阿里山和太魯閣 — 車程長且步道較挑戰，小小孩容易累。',
      'zh-CN': '推荐宜兰一日游（礁溪温泉泡脚、传艺中心DIY、罗东夜市）和九份十分一日游（放天灯是小朋友最爱）。台北经典路线也很适合。避免阿里山和太鲁阁 — 车程长且步道有挑战性。',
      en: 'We recommend the Yilan day trip (Jiaoxi hot spring foot bath, traditional arts DIY, Luodong night market) and the Jiufen-Shifen trip (kids love releasing sky lanterns). The Taipei Classics route (Palace Museum, Taipei 101) also works well. Avoid Alishan and Taroko for young children — long drives and challenging trails.',
      ja: '宜蘭（礁渓温泉・伝芸センターDIY・夜市）と九份十分（ランタン上げが子どもに大人気）がおすすめ。台北クラシック（故宮・101）も好評。阿里山と太魯閣は移動時間が長く小さなお子様には不向きです。',
      ko: '이란 일일투어(자오시 온천, 전통예술 DIY, 야시장)와 지우펀-스펀 투어(천등 날리기가 인기)를 추천합니다. 타이베이 클래식(고궁, 101)도 좋습니다. 아리산과 타로코는 이동 시간이 길어 어린이에게 비추천.',
      th: 'แนะนำอี๋หลาน (แช่เท้าน้ำพุร้อน DIY ตลาดกลางคืน) และจิ่วเฟิ่น-สือเฟิ่น (เด็กๆ ชอบปล่อยโคมลอย) ไทเปคลาสสิก (พิพิธภัณฑ์ 101) ก็ดี หลีกเลี่ยงอาลีซานและทาโรโกะกับเด็กเล็ก',
      vi: 'Đề xuất Nghi Lan (ngâm chân nước nóng, DIY nghệ thuật, chợ đêm) và Cửu Phần-Thập Phần (trẻ em thích thả đèn trời). Đài Bắc Kinh Điển (Cố Cung, 101) cũng phù hợp. Tránh A Lý Sơn và Thái Lỗ Các cho trẻ nhỏ.',
      ms: 'Kami syorkan Yilan (rendam kaki air panas, DIY seni, pasar malam) dan Jiufen-Shifen (kanak-kanak suka lepaskan tanglung). Taipei Classics juga sesuai. Elakkan Alishan dan Taroko untuk kanak-kanak kecil.',
      id: 'Rekomendasi Yilan (rendam kaki air panas, DIY seni, pasar malam) dan Jiufen-Shifen (anak-anak suka lampion). Taipei Classics juga cocok. Hindari Alishan dan Taroko untuk anak kecil.',
      fil: 'Recommended ang Yilan (foot bath, DIY, night market) at Jiufen-Shifen (gustong-gusto ng mga bata ang sky lantern). Taipei Classics okay din. Iwasan ang Alishan at Taroko para sa maliliit na bata.',
    },
  },
  {
    question: {
      'zh-TW': '台灣包車一天大概多少錢？',
      'zh-CN': '台湾包车一天大概多少钱？',
      en: 'How much does a one-day charter car cost in Taiwan?',
      ja: '台湾のチャーター車は1日いくらですか？',
      ko: '대만 전세차 하루 비용은 얼마인가요?',
      th: 'เช่ารถพร้อมคนขับ 1 วันราคาเท่าไหร่?',
      vi: 'Thuê xe riêng 1 ngày ở Đài Loan giá bao nhiêu?',
      ms: 'Berapakah kos sewa kereta satu hari di Taiwan?',
      id: 'Berapa biaya sewa mobil satu hari di Taiwan?',
      fil: 'Magkano ang charter car sa Taiwan para sa isang araw?',
    },
    answer: {
      'zh-TW': '費用依車型和時數而異。請直接透過 RelayGo App 查詢即時報價 — 選擇日期、車型和行程後，系統會自動計算費用，包含油資、過路費和司機費用，不會有隱藏收費。',
      'zh-CN': '费用依车型和时数而异。请通过 RelayGo App 查询即时报价 — 选择日期、车型和行程后，系统会自动计算费用，包含油费、过路费和司机费用，不会有隐藏收费。',
      en: 'Pricing varies by vehicle type and duration. Check the RelayGo app for instant quotes — select your date, vehicle, and itinerary, and the system calculates the total including fuel, tolls, and driver costs. No hidden fees.',
      ja: '料金は車種と時間により異なります。RelayGoアプリで即時見積もりが可能です — 日程・車種・行程を選ぶと、燃料費・通行料・ドライバー費用込みの総額が表示されます。追加料金はありません。',
      ko: '차종과 시간에 따라 다릅니다. RelayGo 앱에서 즉시 견적을 확인하세요 — 날짜, 차종, 일정을 선택하면 유류비, 통행료, 기사비 포함 총액이 자동 계산됩니다.',
      th: 'ราคาขึ้นอยู่กับประเภทรถและจำนวนชั่วโมง เช็คราคาทันทีผ่านแอป RelayGo — เลือกวันที่ ประเภทรถ และเส้นทาง ระบบจะคำนวณค่าใช้จ่ายทั้งหมดรวมน้ำมัน ค่าทางด่วน และค่าคนขับ ไม่มีค่าใช้จ่ายแอบแฝง',
      vi: 'Giá phụ thuộc loại xe và thời gian. Kiểm tra báo giá tức thì trên ứng dụng RelayGo — chọn ngày, loại xe và lịch trình, hệ thống tự động tính tổng bao gồm xăng, phí cầu đường và chi phí tài xế. Không phí ẩn.',
      ms: 'Harga bergantung pada jenis kenderaan dan tempoh. Semak sebut harga segera di aplikasi RelayGo — pilih tarikh, jenis kenderaan dan jadual, sistem akan mengira jumlah termasuk bahan api, tol dan kos pemandu. Tiada caj tersembunyi.',
      id: 'Harga tergantung jenis mobil dan durasi. Cek harga instan di aplikasi RelayGo — pilih tanggal, jenis mobil dan rute, sistem otomatis menghitung total termasuk BBM, tol dan biaya sopir. Tanpa biaya tersembunyi.',
      fil: 'Depende ang presyo sa uri ng sasakyan at oras. I-check ang instant quote sa RelayGo app — piliin ang petsa, sasakyan at ruta, automatic na makalkula ang kabuuan kasama ang gas, toll at driver fee. Walang hidden charges.',
    },
  },
  {
    question: {
      'zh-TW': '桃園機場到台北市區包車要多久？',
      'zh-CN': '桃园机场到台北市区包车要多久？',
      en: 'How long is the charter car ride from Taoyuan Airport to Taipei?',
      ja: '桃園空港から台北市内までチャーター車でどのくらいですか？',
      ko: '타오위안 공항에서 타이베이까지 전세차로 얼마나 걸리나요?',
      th: 'จากสนามบินเถาหยวนไปไทเปใช้เวลานานเท่าไหร่?',
      vi: 'Từ sân bay Đào Viên đến Đài Bắc mất bao lâu?',
      ms: 'Berapa lama dari Lapangan Terbang Taoyuan ke Taipei?',
      id: 'Berapa lama dari Bandara Taoyuan ke Taipei?',
      fil: 'Gaano katagal mula Taoyuan Airport papuntang Taipei?',
    },
    answer: {
      'zh-TW': '桃園國際機場（TPE）到台北市區車程約40-60分鐘，視交通狀況而定。抵達後可透過 RelayGo App 內建聊天功能與司機聯繫，約定出口碰面地點。松山機場（TSA）到台北市區則只需15-20分鐘。',
      'zh-CN': '桃园国际机场到台北市区车程约40-60分钟，视交通而定。抵达后可通过 RelayGo App 内建聊天功能与司机联系，约定出口碰面地点。松山机场到台北市区只需15-20分钟。',
      en: 'Taoyuan International Airport (TPE) to central Taipei takes about 40-60 minutes depending on traffic. After landing, use the in-app chat to coordinate a meeting point at the exit with your driver. From Songshan Airport (TSA), it\'s only 15-20 minutes to downtown.',
      ja: '桃園国際空港から台北市内まで約40〜60分（交通状況による）。到着後、アプリ内チャットでドライバーと出口の待ち合わせ場所を調整できます。松山空港からは15〜20分です。',
      ko: '타오위안 국제공항(TPE)에서 타이베이 시내까지 약 40-60분(교통 상황에 따라 다름). 도착 후 앱 내 채팅으로 기사님과 출구 만남 장소를 조율합니다. 쑹산 공항(TSA)은 15-20분.',
      th: 'สนามบินเถาหยวน (TPE) ไปใจกลางไทเปประมาณ 40-60 นาที หลังลงเครื่องใช้แชทในแอปนัดจุดนัดพบกับคนขับที่ทางออก จากสนามบินซงซาน (TSA) แค่ 15-20 นาที',
      vi: 'Sân bay Đào Viên (TPE) đến trung tâm Đài Bắc khoảng 40-60 phút tùy giao thông. Sau khi hạ cánh, dùng chat trong app để hẹn điểm gặp tài xế ở cửa ra. Từ sân bay Tùng Sơn (TSA) chỉ 15-20 phút.',
      ms: 'Lapangan Terbang Taoyuan (TPE) ke pusat Taipei kira-kira 40-60 minit. Selepas mendarat, gunakan sembang dalam aplikasi untuk menyelaras titik pertemuan di pintu keluar dengan pemandu. Dari Songshan (TSA) hanya 15-20 minit.',
      id: 'Bandara Taoyuan (TPE) ke pusat Taipei sekitar 40-60 menit tergantung lalu lintas. Setelah mendarat, gunakan chat dalam aplikasi untuk koordinasi titik pertemuan di pintu keluar dengan sopir. Dari Bandara Songshan (TSA) hanya 15-20 menit.',
      fil: 'Taoyuan Airport (TPE) papuntang Taipei mga 40-60 minuto depende sa traffic. Pagkatapos lumanding, gamitin ang in-app chat para mag-coordinate ng meeting point sa exit kasama ang driver. Mula Songshan Airport (TSA) 15-20 minuto lang.',
    },
  },
  {
    question: {
      'zh-TW': '包車可以跨城市嗎？例如台北到高雄。',
      'zh-CN': '包车可以跨城市吗？例如台北到高雄。',
      en: 'Can I charter a car for inter-city trips, like Taipei to Kaohsiung?',
      ja: '都市間のチャーター（例：台北→高雄）は可能ですか？',
      ko: '도시 간 전세(예: 타이베이→가오슝)도 가능한가요?',
      th: 'เช่ารถข้ามเมืองได้ไหม เช่น ไทเปไปเกาสง?',
      vi: 'Có thể thuê xe liên tỉnh không, ví dụ Đài Bắc đi Cao Hùng?',
      ms: 'Bolehkah saya sewa kereta antara bandar, contohnya Taipei ke Kaohsiung?',
      id: 'Bisa sewa mobil antar kota, misalnya Taipei ke Kaohsiung?',
      fil: 'Pwede bang mag-charter ng kotse sa pagitan ng mga lungsod, tulad ng Taipei papuntang Kaohsiung?',
    },
    answer: {
      'zh-TW': '可以。RelayGo 提供跨城市包車服務，例如台北出發到日月潭、阿里山、甚至高雄都沒問題。跨區行程會依據距離計算跨區費，報價時會清楚列出，不會有額外費用。',
      'zh-CN': '可以。RelayGo 提供跨城市包车服务，例如台北出发到日月潭、阿里山甚至高雄都没问题。跨区行程会依距离计算跨区费，报价时会清楚列出。',
      en: 'Absolutely. RelayGo offers inter-city charters — Taipei to Sun Moon Lake, Alishan, or even Kaohsiung. Cross-region surcharges are calculated by distance and clearly listed in your quote. No surprise fees.',
      ja: 'もちろん可能です。台北発の日月潭・阿里山・高雄行きなど、都市間チャーターに対応。距離に応じた越境料金が見積もりに明示されます。',
      ko: '네, 가능합니다. 타이베이에서 르웨탄, 아리산, 가오슝까지 도시 간 전세를 제공합니다. 거리에 따른 지역 할증료가 견적에 명시됩니다.',
      th: 'ได้เลย เช่ารถข้ามเมืองจากไทเปไปสุริยันจันทรา อาลีซาน หรือแม้แต่เกาสง ค่าข้ามเขตคำนวณตามระยะทางและแจ้งชัดเจนในใบเสนอราคา',
      vi: 'Hoàn toàn được. RelayGo cung cấp dịch vụ liên tỉnh — Đài Bắc đi Hồ Nhật Nguyệt, A Lý Sơn, hay thậm chí Cao Hùng. Phụ phí liên vùng tính theo khoảng cách, ghi rõ trong báo giá.',
      ms: 'Sudah tentu. RelayGo menawarkan charter antara bandar — Taipei ke Sun Moon Lake, Alishan, atau Kaohsiung. Caj merentas zon dikira mengikut jarak dan disenaraikan dalam sebut harga.',
      id: 'Tentu saja. RelayGo menyediakan charter antar kota — Taipei ke Sun Moon Lake, Alishan, atau Kaohsiung. Biaya lintas wilayah dihitung berdasarkan jarak dan tercantum jelas di penawaran.',
      fil: 'Oo naman. Nag-aalok ang RelayGo ng inter-city charter — Taipei papuntang Sun Moon Lake, Alishan, o Kaohsiung. Ang cross-region surcharge ay kinakalkula base sa distansya at malinaw na nakalista sa quote.',
    },
  },
  {
    question: {
      'zh-TW': '下雨天還能去九份嗎？',
      'zh-CN': '下雨天还能去九份吗？',
      en: 'Can I still visit Jiufen on a rainy day?',
      ja: '雨の日でも九份に行けますか？',
      ko: '비 오는 날에도 지우펀에 갈 수 있나요?',
      th: 'วันฝนตกยังไปจิ่วเฟิ่นได้ไหม?',
      vi: 'Trời mưa có thể đi Cửu Phần được không?',
      ms: 'Bolehkah saya ke Jiufen semasa hujan?',
      id: 'Bisa ke Jiufen saat hujan?',
      fil: 'Pwede pa bang pumunta sa Jiufen kapag umuulan?',
    },
    answer: {
      'zh-TW': '可以，而且九份雨天別有風味！山城裡雲霧繚繞，紅燈籠在霧中更有氛圍。不過九份全程都是石階，雨天路滑務必穿防滑鞋、帶雨具。包車的好處是不用在雨中等公車，逛完直接上車吹冷氣。',
      'zh-CN': '可以，九份雨天别有风味！山城云雾缭绕，红灯笼在雾中更有氛围。不过九份全是石阶，雨天路滑一定穿防滑鞋、带雨具。包车的好处是不用在雨中等车。',
      en: 'Absolutely — Jiufen is actually magical in the rain! Mist swirling through the mountain town with red lanterns glowing through fog creates an incredibly atmospheric scene. Just wear non-slip shoes (the stone stairs get slippery) and bring rain gear. With a charter car, you skip waiting for buses in the rain.',
      ja: 'もちろん行けます — 実は雨の九份は格別です！霧に包まれた山城、霧越しに光る赤い提灯は幻想的。ただし石段が滑りやすいので滑りにくい靴と雨具をお忘れなく。チャーター車なら雨の中でバスを待つ必要がありません。',
      ko: '네, 사실 비 오는 지우펀이 더 멋집니다! 안개 낀 산성마을과 빨간 등불이 환상적. 단, 돌계단이 미끄러우니 미끄럼 방지 신발과 우비 필수. 전세차는 비 속에서 버스 기다릴 필요 없어 편합니다.',
      th: 'ได้เลย จิ่วเฟิ่นวันฝนตกสวยมาก! หมอกเมืองบนเขากับโคมแดงในหมอกบรรยากาศเยี่ยม แต่บันไดหินลื่น ใส่รองเท้ากันลื่นและเตรียมร่ม รถเช่าดีตรงไม่ต้องรอรถบัสตากฝน',
      vi: 'Hoàn toàn được — Cửu Phần dưới mưa rất đẹp! Sương mù bao phủ phố núi, đèn lồng đỏ lấp lánh qua màn sương tạo cảnh tượng mê hoặc. Nhớ đi giày chống trượt và mang áo mưa. Thuê xe thì không cần đợi xe buýt dưới mưa.',
      ms: 'Boleh — Jiufen sebenarnya ajaib semasa hujan! Kabus menyelubungi pekan bukit dengan tanglung merah bersinar melalui kabut. Pakai kasut anti-gelincir dan bawa payung. Dengan kereta sewa, tak perlu menunggu bas dalam hujan.',
      id: 'Bisa — Jiufen saat hujan justru magis! Kabut menyelimuti kota bukit dengan lampion merah menyala. Pakai sepatu anti-selip dan bawa payung. Dengan sewa mobil, tidak perlu tunggu bus kehujanan.',
      fil: 'Oo — ang Jiufen ay mas magical kapag umuulan! Fog sa mountain town na may red lanterns, napaka-atmospheric. Mag-suot ng anti-slip shoes at magdala ng payong. Sa charter car, hindi kailangan maghintay ng bus sa ulan.',
    },
  },
];
